### ISSUE TITLE
User story: Intuitive Ground Server to Client Pairing

### ISSUE THREAD

**Issue by rjcorwin** [open-eio/Open-Ground-SDK#1]
This user story is yet to be written as we are still brainstorming the best way to fulfill the requirement.

![601f605a-944b-11e4-8399-d2640400a7b9](https://cloud.githubusercontent.com/assets/156575/5684562/85704132-97ff-11e4-9529-2724a4411322.png)

Interesting links
- [from over the summer with OLE, this worked](http://andrewmichaelsmith.com/2013/08/raspberry-pi-wi-fi-honeypot/)
- http://elinux.org/RPI-Wireless-Hotspot
- http://www.pi-point.co.uk/
  http://raspberrypihq.com/how-to-turn-a-raspberry-pi-into-a-wifi-router/
- http://www.rpiblog.com/2012/12/turn-raspberry-pi-into-wireless-access.html

interesting discussions
- [discovery of mDNS URLs on Physical Web](https://github.com/google/physical-web/pull/226#issuecomment-68606760)
- [From Ground Computing Group: It's time to make mDNS/Zeroconf/Bonjour usable on Android](https://groups.google.com/forum/#!topic/groundcomputing/5MYwcvN8wWY)

What matters seems to be whether or not the WiFi USB hardware is AP mode capable, AKA promiscuous mode.

Thinking about the [geofence technique](http://en.wikipedia.org/wiki/Geo-fence) could be useful in making this user friendly and performant.  For example, activating WiFi link between the Ground Server and the Client given the GPS coordinates of the Ground Server and the Client, this would be both user friendly and save on energy by not broadcasting when there is no point in doing so.

The goal at the moment is to achieve and test the following configurations ([see link for diagrams](https://docs.google.com/a/rjsteinert.com/presentation/d/1lbhm5o4YBbJDbv3keoYo3rjQe9nle4jeCNrZOh7VxRs/edit#slide=id.g5c8dd8351_0106))
- [ ] Pipe Network Config 1
- [ ] Pipe Network Config 2
- [ ] Pipe Network Config 3
- [ ] Pipe Network Config 4

**Comment by rjsteinert** [comment]
interesting discussions
- [discovery of mDNS URLs on Physical Web](https://github.com/google/physical-web/pull/226#issuecomment-68606760)
- [From Ground Computing Group: It's time to make mDNS/Zeroconf/Bonjour usable on Android](https://groups.google.com/forum/#!topic/groundcomputing/5MYwcvN8wWY)

**Comment by rjcorwin** [comment]
Moved to https://github.com/open-eio/Open-Pipe-Kit/issues/2
